version: '3.8'

services:
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=trello_clone_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=Y3SQSvDrDA6Q23BW
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro 
    #restart: always
  backend:
    depends_on:
      - mongodb
    build: .
    env_file: ./env
    ports:
      - 8080:8080
    stdin_open: true
    tty: true
    #restart: always